/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_elements_edgelib_EdgelibFile */

#ifndef _Included_nl_elements_edgelib_EdgelibFile
#define _Included_nl_elements_edgelib_EdgelibFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_elements_edgelib_EdgelibFile
 * Method:    sinkdata
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibFile_sinkdata
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibFile
 * Method:    debug
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibFile_debug
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
