/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_elements_edgelib_EdgelibApp */

#ifndef _Included_nl_elements_edgelib_EdgelibApp
#define _Included_nl_elements_edgelib_EdgelibApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    edgeStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibApp_edgeStart
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    idleFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibApp_idleFrame
  (JNIEnv *, jobject);

/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    getSustainLoop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_elements_edgelib_EdgelibApp_getSustainLoop
  (JNIEnv *, jobject);

/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    keyEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibApp_keyEvent
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    touchEvent
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibApp_touchEvent
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    focusChanged
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibApp_focusChanged
  (JNIEnv *, jobject, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibApp
 * Method:    getOpenGL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_elements_edgelib_EdgelibApp_getOpenGL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
