/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_elements_edgelib_EdgelibUtil */

#ifndef _Included_nl_elements_edgelib_EdgelibUtil
#define _Included_nl_elements_edgelib_EdgelibUtil
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
