/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_elements_edgelib_EdgelibView */

#ifndef _Included_nl_elements_edgelib_EdgelibView
#define _Included_nl_elements_edgelib_EdgelibView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_elements_edgelib_EdgelibView
 * Method:    onNewBuffer
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibView_onNewBuffer
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibView
 * Method:    onChangeBuffer
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibView_onChangeBuffer
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibView
 * Method:    onDrawEvent
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibView_onDrawEvent
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     nl_elements_edgelib_EdgelibView
 * Method:    trackEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_nl_elements_edgelib_EdgelibView_trackEvent
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
