/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_elements_edgelib_eventcore_Eventcore */

#ifndef _Included_nl_elements_edgelib_eventcore_Eventcore
#define _Included_nl_elements_edgelib_eventcore_Eventcore
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
